version: '3'

services:
  app:
    container_name: docsify
    image: localhost/docsify:latest
    privileged: true
    user: ${HOST_USER_ID:-0}:${HOST_GROUP_ID:-0}
    ports:
      - ${APP_PORT:-3000}:3000
    volumes:
      - ./tests:/docs
